# Generated by Django 3.2.4 on 2021-11-25 08:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BeamModel',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('length', models.FloatField(default=0)),
                ('E', models.FloatField(default=200000000000)),
                ('I', models.FloatField(default=9.05e-06)),
                ('A', models.FloatField(default=0.23)),
            ],
        ),
        migrations.CreateModel(
            name='UnitOptionsModel',
            fields=[
                ('units', models.CharField(default='SI', max_length=64)),
                ('length', models.CharField(default='m', max_length=64)),
                ('force', models.CharField(default='N', max_length=64)),
                ('moment', models.CharField(default='N.m', max_length=64)),
                ('distributed', models.CharField(default='N/m', max_length=64)),
                ('stiffness', models.CharField(default='N/m', max_length=64)),
                ('A', models.CharField(default='m2', max_length=64)),
                ('E', models.CharField(default='Pa', max_length=64)),
                ('I', models.CharField(default='m4', max_length=64)),
                ('deflection', models.CharField(default='m', max_length=64)),
                ('beam', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='units', serialize=False, to='beam.beammodel')),
            ],
        ),
        migrations.CreateModel(
            name='SupportModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('coordinate', models.FloatField(default=0)),
                ('support', models.CharField(choices=[('Fixed', 'Fixed'), ('Pinned', 'Pinned'), ('Roller', 'Roller')], default='Fixed', max_length=10)),
                ('beam', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='supports', to='beam.beammodel')),
            ],
        ),
        migrations.CreateModel(
            name='QueryModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('query', models.FloatField(default=0)),
                ('beam', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='queries', to='beam.beammodel')),
            ],
        ),
        migrations.CreateModel(
            name='PointTorqueModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('coordinate', models.FloatField(default=0)),
                ('torque', models.FloatField(default=0)),
                ('beam', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='point_torques', to='beam.beammodel')),
            ],
        ),
        migrations.CreateModel(
            name='PointLoadModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('coordinate', models.FloatField(default=0)),
                ('force', models.FloatField(default=0)),
                ('angle', models.FloatField(default=90)),
                ('beam', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='point_loads', to='beam.beammodel')),
            ],
        ),
        migrations.CreateModel(
            name='DistributedLoadModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_coordinate', models.FloatField(default=0)),
                ('end_coordinate', models.FloatField(default=0)),
                ('start_load', models.FloatField(default=0)),
                ('end_load', models.FloatField(default=0)),
                ('beam', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='distributed_loads', to='beam.beammodel')),
            ],
        ),
    ]
