# Generated by Django 3.2.4 on 2021-11-28 07:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('beam', '0002_auto_20211128_1750'),
    ]

    operations = [
        migrations.RenameField(
            model_name='pointloadmodel',
            old_name='coordinate',
            new_name='pl_coordinate',
        ),
        migrations.RenameField(
            model_name='pointtorquemodel',
            old_name='coordinate',
            new_name='pt_coordinate',
        ),
        migrations.RenameField(
            model_name='supportmodel',
            old_name='coordinate',
            new_name='s_coordinate',
        ),
        migrations.RenameField(
            model_name='unitoptionsmodel',
            old_name='A',
            new_name='A_u',
        ),
        migrations.RenameField(
            model_name='unitoptionsmodel',
            old_name='E',
            new_name='E_u',
        ),
        migrations.RenameField(
            model_name='unitoptionsmodel',
            old_name='I',
            new_name='I_u',
        ),
        migrations.RenameField(
            model_name='unitoptionsmodel',
            old_name='deflection',
            new_name='deflection_u',
        ),
        migrations.RenameField(
            model_name='unitoptionsmodel',
            old_name='distributed',
            new_name='distributed_u',
        ),
        migrations.RenameField(
            model_name='unitoptionsmodel',
            old_name='force',
            new_name='force_u',
        ),
        migrations.RenameField(
            model_name='unitoptionsmodel',
            old_name='length',
            new_name='length_u',
        ),
        migrations.RenameField(
            model_name='unitoptionsmodel',
            old_name='moment',
            new_name='moment_u',
        ),
        migrations.RenameField(
            model_name='unitoptionsmodel',
            old_name='stiffness',
            new_name='stiffness_u',
        ),
    ]
