# Generated by Django 3.2.4 on 2021-11-28 07:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('beam', '0003_auto_20211128_1807'),
    ]

    operations = [
        migrations.RenameField(
            model_name='pointloadmodel',
            old_name='pl_coordinate',
            new_name='coordinate',
        ),
        migrations.RenameField(
            model_name='pointtorquemodel',
            old_name='pt_coordinate',
            new_name='coordinate',
        ),
        migrations.RenameField(
            model_name='supportmodel',
            old_name='s_coordinate',
            new_name='coordinate',
        ),
        migrations.RenameField(
            model_name='unitoptionsmodel',
            old_name='A_u',
            new_name='A',
        ),
        migrations.RenameField(
            model_name='unitoptionsmodel',
            old_name='E_u',
            new_name='E',
        ),
        migrations.RenameField(
            model_name='unitoptionsmodel',
            old_name='I_u',
            new_name='I',
        ),
        migrations.RenameField(
            model_name='unitoptionsmodel',
            old_name='length_u',
            new_name='deflection',
        ),
        migrations.RenameField(
            model_name='unitoptionsmodel',
            old_name='distributed_u',
            new_name='distributed',
        ),
        migrations.RenameField(
            model_name='unitoptionsmodel',
            old_name='force_u',
            new_name='force',
        ),
        migrations.RenameField(
            model_name='unitoptionsmodel',
            old_name='deflection_u',
            new_name='length',
        ),
        migrations.RenameField(
            model_name='unitoptionsmodel',
            old_name='moment_u',
            new_name='moment',
        ),
        migrations.RenameField(
            model_name='unitoptionsmodel',
            old_name='stiffness_u',
            new_name='stiffness',
        ),
    ]
