# Generated by Django 3.2.4 on 2022-01-10 08:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('beam', '0006_auto_20220110_1825'),
    ]

    operations = [
        migrations.AlterField(
            model_name='unitoptionsmodel',
            name='units',
            field=models.CharField(choices=[('metric', 'metric'), ('imperial', 'imperial')], default='SI', max_length=64),
        ),
    ]
